---
title: Type on Strap
timezone: UTC
collections:
  portfolio:
    title: Portfolio
    output: true
    permalink: "/:collection/:name"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: ''
url: https://test01102.github.io
description: A website with blog posts and pages
avatar: assets/img/triangle.png
favicon: assets/favicon.ico
header_text: abcd
header_feature_image: assets/img/pexels/triangular.jpeg
footer_text: 'Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type
  on Strap</a>

'
excerpt: true
post_navigation: true
color_image: "/assets/img/lineart.png"
katex: true
google_analytics: 
disqus_shortname: 
layout_variables: 
footer_icons: 
share_buttons: 
authors: 
language: 
paginate: 5
paginate_path: blog/page:num
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-feed
exclude:
- ".jekyll-cache"
- Gemfile
- Gemfile.lock
- type-on-strap.gemspec
- "*.gem"
- ".idea"
- vendor/*
- LICENSE
- README.md
- screenshot.png
- assets/package.json
- assets/node_modules
- assets/gulpfile.js
remote_theme: sylhare/Type-on-Strap
